[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && python manage.py createsuperuser --noinput || true && python manage.py collectstatic --noinput && gunicorn language_listening_practice_app.wsgi"
