# Generated by Django 5.2.7 on 2025-10-06 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('shadow', 'Shadowing'), ('transcribe', 'Transcription'), ('multiple_choice', 'Multiple Choice')])),
                ('question', models.TextField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('show_video', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('exercises', models.ManyToManyField(to='language_listening_practice_app.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='youtube_clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_listening_practice_app.youtubeclip'),
        ),
    ]
