# Generated by Django 5.2.7 on 2025-10-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_listening_practice_app', '0003_exerciseattempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
