# Generated by Django 5.2.7 on 2025-10-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_listening_practice_app', '0004_exercise_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeclip',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
